# makefile for building gammon

CC=gcc
RM=rm -f
CFLAGS=-O3 -Wall -Wconversion -pedantic $(EXTRA_FLAGS) $(INCLUDES)
INCLUDES=
LIBS=-lm

all: plsa hmm

plsa: plsa.o reader.o docinfo.o hashtable.o random.o utils.o
	$(CC) $^ $(LIBS) $(EXTRA_LD_FLAGS) -o $@

hmm: hmm.o reader.o docinfo.o hashtable.o random.o utils.o
	$(CC) $^ $(LIBS) $(EXTRA_LD_FLAGS) -o $@

.c.o:
	$(CC) $(CFLAGS) -c $< -o $@

.PHONY: clean

clean:
	$(RM) plsa hmm *.o

# automatically generated by `gcc -MM *.c`
# DO NOT DELETE
plsa.o: plsa.c plsa.h docinfo.h hashtable.h reader.h utils.h random.h
hmm.o: hmm.c hmm.h docinfo.h hashtable.h reader.h utils.h random.h
docinfo.o: docinfo.c docinfo.h hashtable.h reader.h utils.h
hashtable.o: hashtable.c hashtable.h utils.h
reader.o: reader.c reader.h utils.h
random.o: random.c random.h
utils.o: utils.c utils.h
